// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package delete

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockURLDeleter creates a new instance of MockURLDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLDeleter {
	mock := &MockURLDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockURLDeleter is an autogenerated mock type for the URLDeleter type
type MockURLDeleter struct {
	mock.Mock
}

type MockURLDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLDeleter) EXPECT() *MockURLDeleter_Expecter {
	return &MockURLDeleter_Expecter{mock: &_m.Mock}
}

// DeleteURL provides a mock function for the type MockURLDeleter
func (_mock *MockURLDeleter) DeleteURL(alias string) error {
	ret := _mock.Called(alias)

	if len(ret) == 0 {
		panic("no return value specified for DeleteURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(alias)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockURLDeleter_DeleteURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteURL'
type MockURLDeleter_DeleteURL_Call struct {
	*mock.Call
}

// DeleteURL is a helper method to define mock.On call
//   - alias string
func (_e *MockURLDeleter_Expecter) DeleteURL(alias any) *MockURLDeleter_DeleteURL_Call {
	return &MockURLDeleter_DeleteURL_Call{Call: _e.mock.On("DeleteURL", alias)}
}

func (_c *MockURLDeleter_DeleteURL_Call) Run(run func(alias string)) *MockURLDeleter_DeleteURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockURLDeleter_DeleteURL_Call) Return(err error) *MockURLDeleter_DeleteURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockURLDeleter_DeleteURL_Call) RunAndReturn(run func(alias string) error) *MockURLDeleter_DeleteURL_Call {
	_c.Call.Return(run)
	return _c
}
